local gui = require("lib.gui")

local main = gui.createFrame("main")
main:addLabel()
    :setText("Computer UI")
    :setPosition(1, 1)

main:addDropdown()
    :setOptions({"Option 1", "Option 2", "Option 3"})
    :setPosition(1, 3)
    :setBackgroundColour(colours.lightGrey)
    :setTextColour(colours.white)
    :setSelBackgroundColor(colours.blue)
    :setSelTextColor(colours.red)
    :onSelect(function(option)
        main:addLabel()
            :setText("Selected: " .. option)
            :setPosition(1, 7)
            :setTextColour(colors.green)
            :draw()
    end)

main:addKeyinput()
    :setPosition(1, 9)
    :setSize(20, 1)
    :setBackgroundColour(colors.green)
    :setTextColour(colors.white)
    :onSubmit(function(text)
        main:addLabel()
            :setText("Input: " .. text)
            :setPosition(1, 10)
            :setTextColour(colors.yellow)
            :draw()
    end)

local monitor = peripheral.find("monitor")
if monitor then
    monitor.setTextScale(1)
    monitor.clear()
    local monitorFrame = gui.createFrame("monitor"):setTerm(monitor)
    monitorFrame:addButton()
        :setText("Monitor Button")
        :setPosition(2, 2)
        :setBackgroundColour(colors.green)
        :onClick(function()
            monitorFrame:addLabel()
                :setText("Button Clicked!")
                :setPosition(2, 4)
                :setTextColour(colors.red)
                :draw()
        end)
end

gui.run("main")
